import type { DocsTranslation } from "@/lib/i18n/types";

const pascal = (name: string) =>
  name.split("-").map((w) => w[0].toUpperCase() + w.slice(1)).join("");

function checkList(label: string, en: string[], ru: unknown, errors: string[]) {
  if (!Array.isArray(ru) || ru.some((v) => typeof v !== "string" || v.trim() === "")) {
    errors.push(`${label}: expected ${en.length} non-empty strings`);
    return;
  }
  if (ru.length !== en.length) {
    errors.push(`${label}: expected ${en.length} items, got ${ru.length}`);
  }
}

/**
 * Returns human-readable errors; an empty array means valid.
 *
 * The length assertions are the important ones. Translation is machine-produced
 * and unreviewed, and a model silently dropping the fourth pitfall is the
 * realistic failure mode — undetectable by eye, trivial to detect here.
 */
export function validateTranslation(en: DocsTranslation, candidate: unknown): string[] {
  const errors: string[] = [];
  if (typeof candidate !== "object" || candidate === null || Array.isArray(candidate)) {
    return ["not a JSON object"];
  }
  const ru = candidate as Partial<DocsTranslation>;

  for (const key of ["whatItIs", "whyItMatters", "usage"] as const) {
    if (typeof ru[key] !== "string" || ru[key]!.trim() === "") errors.push(`${key}: missing or empty`);
  }

  if (typeof ru.anatomy !== "object" || ru.anatomy === null) {
    errors.push("anatomy: missing");
  } else {
    const enKeys = Object.keys(en.anatomy);
    const ruKeys = Object.keys(ru.anatomy);
    for (const k of enKeys) if (!ruKeys.includes(k)) errors.push(`anatomy: missing slot "${k}"`);
    for (const k of ruKeys) if (!enKeys.includes(k)) errors.push(`anatomy: unknown slot "${k}"`);
  }

  checkList("dos", en.dos, ru.dos, errors);
  checkList("donts", en.donts, ru.donts, errors);
  checkList("pitfalls", en.pitfalls, ru.pitfalls, errors);

  const a = ru.accessibility;
  if (typeof a !== "object" || a === null) {
    errors.push("accessibility: missing");
  } else {
    checkList("accessibility.keyboard", en.accessibility.keyboard, a.keyboard, errors);
    checkList("accessibility.screenReader", en.accessibility.screenReader, a.screenReader, errors);
    if (en.accessibility.focus) {
      checkList("accessibility.focus", en.accessibility.focus, a.focus, errors);
    } else if (a.focus !== undefined) {
      errors.push("accessibility.focus: present but absent in English");
    }
  }

  return errors;
}

export function renderOverlayFile(name: string, hash: string, ru: DocsTranslation): string {
  return `// GENERATED by scripts/i18n-sync.mts. Do not edit by hand — edits are
// discarded on the next sync. Regenerate with: pnpm i18n:sync
// @source-hash: ${hash}
import type { DocsTranslation } from "@/lib/i18n/types";

export const ${pascal(name)}Ru: DocsTranslation = ${JSON.stringify(ru, null, 2)};
`;
}
