import { describe, expect, it } from "vitest";

import type { DocsTranslation } from "@/lib/i18n/types";
import { renderOverlayFile, validateTranslation } from "./i18n-validate";

const EN: DocsTranslation = {
  whatItIs: "A.",
  whyItMatters: "B.",
  usage: "C.",
  anatomy: { "x-root": "Root.", "x-header": "Header." },
  dos: ["One.", "Two."],
  donts: ["No."],
  accessibility: { keyboard: ["K1.", "K2."], screenReader: ["S."] },
  pitfalls: ["P."],
};

const GOOD: DocsTranslation = {
  whatItIs: "А.",
  whyItMatters: "Б.",
  usage: "В.",
  anatomy: { "x-root": "Корень.", "x-header": "Шапка." },
  dos: ["Раз.", "Два."],
  donts: ["Нет."],
  accessibility: { keyboard: ["К1.", "К2."], screenReader: ["С."] },
  pitfalls: ["П."],
};

describe("validateTranslation", () => {
  it("accepts a well-formed translation", () => {
    expect(validateTranslation(EN, GOOD)).toEqual([]);
  });

  it("rejects a non-object", () => {
    expect(validateTranslation(EN, "nope").length).toBeGreaterThan(0);
  });

  it("rejects a dropped list item — the realistic failure mode", () => {
    const short = { ...GOOD, pitfalls: [] };
    expect(validateTranslation(EN, short).join()).toContain("pitfalls");
  });

  it("rejects a dropped accessibility note", () => {
    const short = { ...GOOD, accessibility: { keyboard: ["К1."], screenReader: ["С."] } };
    expect(validateTranslation(EN, short).join()).toContain("keyboard");
  });

  it("rejects an unknown anatomy key", () => {
    const bad = { ...GOOD, anatomy: { ...GOOD.anatomy, "x-invented": "Выдумка." } };
    expect(validateTranslation(EN, bad).join()).toContain("x-invented");
  });

  it("rejects a missing anatomy key", () => {
    const bad = { ...GOOD, anatomy: { "x-root": "Корень." } };
    expect(validateTranslation(EN, bad).join()).toContain("x-header");
  });

  it("rejects an empty-string anatomy value — a present key is not enough", () => {
    const bad = { ...GOOD, anatomy: { ...GOOD.anatomy, "x-root": "" } };
    expect(validateTranslation(EN, bad).join()).toContain('anatomy: slot "x-root"');
  });

  it("rejects a non-string anatomy value", () => {
    const bad = { ...GOOD, anatomy: { ...GOOD.anatomy, "x-root": 42 } };
    expect(validateTranslation(EN, bad).join()).toContain('anatomy: slot "x-root"');
  });

  it("rejects an empty string field", () => {
    expect(validateTranslation(EN, { ...GOOD, usage: "" }).join()).toContain("usage");
  });

  it("rejects a focus arm the English does not have", () => {
    const bad = { ...GOOD, accessibility: { ...GOOD.accessibility, focus: ["Ф."] } };
    expect(validateTranslation(EN, bad).join()).toContain("focus");
  });
});

describe("renderOverlayFile", () => {
  it("stamps the generated header and the source hash", () => {
    const src = renderOverlayFile("empty-state", "abc123def4567890", GOOD);
    expect(src.startsWith("// GENERATED by scripts/i18n-sync.mts.")).toBe(true);
    expect(src).toContain("// @source-hash: abc123def4567890");
  });

  it("exports a PascalCase const typed DocsTranslation", () => {
    const src = renderOverlayFile("empty-state", "abc123def4567890", GOOD);
    expect(src).toContain("export const EmptyStateRu: DocsTranslation =");
  });

  it("round-trips through JSON", () => {
    const src = renderOverlayFile("empty-state", "h", GOOD);
    const json = src.slice(src.indexOf("= ") + 2, src.lastIndexOf(";"));
    expect(JSON.parse(json)).toEqual(GOOD);
  });
});
