// GENERATED by scripts/gen-wiring.mts. Do not edit.
import type { ComponentType } from "react";

import AccountMenuDemo from "@/components/demos/account-menu-demo";
import AppSidebarDemo from "@/components/demos/app-sidebar-demo";
import AppTopbarDemo from "@/components/demos/app-topbar-demo";
import ChoiceChipsDemo from "@/components/demos/choice-chips-demo";
import CostChipDemo from "@/components/demos/cost-chip-demo";
import DateSectionDemo from "@/components/demos/date-section-demo";
import EntityRowDemo from "@/components/demos/entity-row-demo";
import FeatureCardRowDemo from "@/components/demos/feature-card-row-demo";
import FieldRowDemo from "@/components/demos/field-row-demo";
import FilterBarDemo from "@/components/demos/filter-bar-demo";
import GenSettingsBarDemo from "@/components/demos/gen-settings-bar-demo";
import HeroOmniboxDemo from "@/components/demos/hero-omnibox-demo";
import KbdDemo from "@/components/demos/kbd-demo";
import ModalityRailDemo from "@/components/demos/modality-rail-demo";
import PreviewTileDemo from "@/components/demos/preview-tile-demo";
import PromoCardDemo from "@/components/demos/promo-card-demo";
import RecentGridDemo from "@/components/demos/recent-grid-demo";
import RecommendationCardDemo from "@/components/demos/recommendation-card-demo";
import ResetAffordanceDemo from "@/components/demos/reset-affordance-demo";
import SectionHeaderDemo from "@/components/demos/section-header-demo";
import ShortcutsSheetDemo from "@/components/demos/shortcuts-sheet-demo";
import SidebarNavDemo from "@/components/demos/sidebar-nav-demo";
import StatReadoutDemo from "@/components/demos/stat-readout-demo";
import ThreadListDemo from "@/components/demos/thread-list-demo";
import WorkspaceSwitcherDemo from "@/components/demos/workspace-switcher-demo";

export const demos: Record<string, ComponentType> = {
  "account-menu": AccountMenuDemo,
  "app-sidebar": AppSidebarDemo,
  "app-topbar": AppTopbarDemo,
  "choice-chips": ChoiceChipsDemo,
  "cost-chip": CostChipDemo,
  "date-section": DateSectionDemo,
  "entity-row": EntityRowDemo,
  "feature-card-row": FeatureCardRowDemo,
  "field-row": FieldRowDemo,
  "filter-bar": FilterBarDemo,
  "gen-settings-bar": GenSettingsBarDemo,
  "hero-omnibox": HeroOmniboxDemo,
  "kbd": KbdDemo,
  "modality-rail": ModalityRailDemo,
  "preview-tile": PreviewTileDemo,
  "promo-card": PromoCardDemo,
  "recent-grid": RecentGridDemo,
  "recommendation-card": RecommendationCardDemo,
  "reset-affordance": ResetAffordanceDemo,
  "section-header": SectionHeaderDemo,
  "shortcuts-sheet": ShortcutsSheetDemo,
  "sidebar-nav": SidebarNavDemo,
  "stat-readout": StatReadoutDemo,
  "thread-list": ThreadListDemo,
  "workspace-switcher": WorkspaceSwitcherDemo,
};
