// GENERATED by scripts/gen-wiring.mts. Do not edit.
import type { ComponentType } from "react";

import AccountMenuDemo from "@/components/demos/account-menu-demo";
import AnswerBlockDemo from "@/components/demos/answer-block-demo";
import AppSidebarDemo from "@/components/demos/app-sidebar-demo";
import AppTopbarDemo from "@/components/demos/app-topbar-demo";
import AutonomySelectorDemo from "@/components/demos/autonomy-selector-demo";
import ChoiceChipsDemo from "@/components/demos/choice-chips-demo";
import CitationRefDemo from "@/components/demos/citation-ref-demo";
import ContextChipsDemo from "@/components/demos/context-chips-demo";
import CostChipDemo from "@/components/demos/cost-chip-demo";
import CreditsIndicatorDemo from "@/components/demos/credits-indicator-demo";
import DateSectionDemo from "@/components/demos/date-section-demo";
import DisclaimerNoteDemo from "@/components/demos/disclaimer-note-demo";
import EntityRowDemo from "@/components/demos/entity-row-demo";
import EscalationHandoffDemo from "@/components/demos/escalation-handoff-demo";
import FeatureCardRowDemo from "@/components/demos/feature-card-row-demo";
import FeedbackDemo from "@/components/demos/feedback-demo";
import FieldRowDemo from "@/components/demos/field-row-demo";
import FilterBarDemo from "@/components/demos/filter-bar-demo";
import GenSettingsBarDemo from "@/components/demos/gen-settings-bar-demo";
import GenerationPanelDemo from "@/components/demos/generation-panel-demo";
import GenerationQueueDemo from "@/components/demos/generation-queue-demo";
import GenerationWizardDemo from "@/components/demos/generation-wizard-demo";
import HeroOmniboxDemo from "@/components/demos/hero-omnibox-demo";
import KbdDemo from "@/components/demos/kbd-demo";
import MediaPromptBarDemo from "@/components/demos/media-prompt-bar-demo";
import MemberGateRowDemo from "@/components/demos/member-gate-row-demo";
import ModalityRailDemo from "@/components/demos/modality-rail-demo";
import ModeTabsDemo from "@/components/demos/mode-tabs-demo";
import ModelPickerDemo from "@/components/demos/model-picker-demo";
import ParameterPanelDemo from "@/components/demos/parameter-panel-demo";
import PresetGridDemo from "@/components/demos/preset-grid-demo";
import PreviewTileDemo from "@/components/demos/preview-tile-demo";
import PricingTableDemo from "@/components/demos/pricing-table-demo";
import PromoCardDemo from "@/components/demos/promo-card-demo";
import QuotaMeterDemo from "@/components/demos/quota-meter-demo";
import QuoteReplyDemo from "@/components/demos/quote-reply-demo";
import RecentGridDemo from "@/components/demos/recent-grid-demo";
import RecommendationCardDemo from "@/components/demos/recommendation-card-demo";
import ReferenceStripDemo from "@/components/demos/reference-strip-demo";
import ResetAffordanceDemo from "@/components/demos/reset-affordance-demo";
import RunButtonDemo from "@/components/demos/run-button-demo";
import SafetyBlockDemo from "@/components/demos/safety-block-demo";
import SectionHeaderDemo from "@/components/demos/section-header-demo";
import ShortcutsSheetDemo from "@/components/demos/shortcuts-sheet-demo";
import SidebarNavDemo from "@/components/demos/sidebar-nav-demo";
import SkillMenuDemo from "@/components/demos/skill-menu-demo";
import SlotSummaryDemo from "@/components/demos/slot-summary-demo";
import SourceCardsDemo from "@/components/demos/source-cards-demo";
import StatReadoutDemo from "@/components/demos/stat-readout-demo";
import TaskTrayDemo from "@/components/demos/task-tray-demo";
import ThreadListDemo from "@/components/demos/thread-list-demo";
import TtsComposerDemo from "@/components/demos/tts-composer-demo";
import VoiceCloneRecorderDemo from "@/components/demos/voice-clone-recorder-demo";
import WorkspaceSwitcherDemo from "@/components/demos/workspace-switcher-demo";

export const demos: Record<string, ComponentType> = {
  "account-menu": AccountMenuDemo,
  "answer-block": AnswerBlockDemo,
  "app-sidebar": AppSidebarDemo,
  "app-topbar": AppTopbarDemo,
  "autonomy-selector": AutonomySelectorDemo,
  "choice-chips": ChoiceChipsDemo,
  "citation-ref": CitationRefDemo,
  "context-chips": ContextChipsDemo,
  "cost-chip": CostChipDemo,
  "credits-indicator": CreditsIndicatorDemo,
  "date-section": DateSectionDemo,
  "disclaimer-note": DisclaimerNoteDemo,
  "entity-row": EntityRowDemo,
  "escalation-handoff": EscalationHandoffDemo,
  "feature-card-row": FeatureCardRowDemo,
  "feedback": FeedbackDemo,
  "field-row": FieldRowDemo,
  "filter-bar": FilterBarDemo,
  "gen-settings-bar": GenSettingsBarDemo,
  "generation-panel": GenerationPanelDemo,
  "generation-queue": GenerationQueueDemo,
  "generation-wizard": GenerationWizardDemo,
  "hero-omnibox": HeroOmniboxDemo,
  "kbd": KbdDemo,
  "media-prompt-bar": MediaPromptBarDemo,
  "member-gate-row": MemberGateRowDemo,
  "modality-rail": ModalityRailDemo,
  "mode-tabs": ModeTabsDemo,
  "model-picker": ModelPickerDemo,
  "parameter-panel": ParameterPanelDemo,
  "preset-grid": PresetGridDemo,
  "preview-tile": PreviewTileDemo,
  "pricing-table": PricingTableDemo,
  "promo-card": PromoCardDemo,
  "quota-meter": QuotaMeterDemo,
  "quote-reply": QuoteReplyDemo,
  "recent-grid": RecentGridDemo,
  "recommendation-card": RecommendationCardDemo,
  "reference-strip": ReferenceStripDemo,
  "reset-affordance": ResetAffordanceDemo,
  "run-button": RunButtonDemo,
  "safety-block": SafetyBlockDemo,
  "section-header": SectionHeaderDemo,
  "shortcuts-sheet": ShortcutsSheetDemo,
  "sidebar-nav": SidebarNavDemo,
  "skill-menu": SkillMenuDemo,
  "slot-summary": SlotSummaryDemo,
  "source-cards": SourceCardsDemo,
  "stat-readout": StatReadoutDemo,
  "task-tray": TaskTrayDemo,
  "thread-list": ThreadListDemo,
  "tts-composer": TtsComposerDemo,
  "voice-clone-recorder": VoiceCloneRecorderDemo,
  "workspace-switcher": WorkspaceSwitcherDemo,
};
