// GENERATED by scripts/gen-wiring.mts. Do not edit.
import type { ComponentType } from "react";

import AccountMenuDemo from "@/components/demos/account-menu-demo";
import ActionStackDemo from "@/components/demos/action-stack-demo";
import AiDocBlockDemo from "@/components/demos/ai-doc-block-demo";
import AiToolsMenuDemo from "@/components/demos/ai-tools-menu-demo";
import AnswerBlockDemo from "@/components/demos/answer-block-demo";
import AppSidebarDemo from "@/components/demos/app-sidebar-demo";
import AppTopbarDemo from "@/components/demos/app-topbar-demo";
import ApprovalCardDemo from "@/components/demos/approval-card-demo";
import ArtifactGridDemo from "@/components/demos/artifact-grid-demo";
import ArtifactShellDemo from "@/components/demos/artifact-shell-demo";
import AssetDetailDemo from "@/components/demos/asset-detail-demo";
import AssetLibraryDemo from "@/components/demos/asset-library-demo";
import AuthShellDemo from "@/components/demos/auth-shell-demo";
import AutonomySelectorDemo from "@/components/demos/autonomy-selector-demo";
import ChatShellDemo from "@/components/demos/chat-shell-demo";
import ChoiceChipsDemo from "@/components/demos/choice-chips-demo";
import CitationRefDemo from "@/components/demos/citation-ref-demo";
import CoachMarkDemo from "@/components/demos/coach-mark-demo";
import CompareViewerDemo from "@/components/demos/compare-viewer-demo";
import ConnectionManagerDemo from "@/components/demos/connection-manager-demo";
import ContextChipsDemo from "@/components/demos/context-chips-demo";
import ContextToolbarDemo from "@/components/demos/context-toolbar-demo";
import CostChipDemo from "@/components/demos/cost-chip-demo";
import CreditsIndicatorDemo from "@/components/demos/credits-indicator-demo";
import DataViewsDemo from "@/components/demos/data-views-demo";
import DateSectionDemo from "@/components/demos/date-section-demo";
import DetailViewShellDemo from "@/components/demos/detail-view-shell-demo";
import DiffReviewDemo from "@/components/demos/diff-review-demo";
import DisclaimerNoteDemo from "@/components/demos/disclaimer-note-demo";
import DocsShellDemo from "@/components/demos/docs-shell-demo";
import DrawingToolsDemo from "@/components/demos/drawing-tools-demo";
import EmptyStateDemo from "@/components/demos/empty-state-demo";
import EntityRowDemo from "@/components/demos/entity-row-demo";
import EnvStatusDemo from "@/components/demos/env-status-demo";
import EscalationHandoffDemo from "@/components/demos/escalation-handoff-demo";
import ExploreGalleryDemo from "@/components/demos/explore-gallery-demo";
import ExploreShellDemo from "@/components/demos/explore-shell-demo";
import FeatureAnnouncementDemo from "@/components/demos/feature-announcement-demo";
import FeatureCardRowDemo from "@/components/demos/feature-card-row-demo";
import FeedbackDemo from "@/components/demos/feedback-demo";
import FieldRowDemo from "@/components/demos/field-row-demo";
import FilterBarDemo from "@/components/demos/filter-bar-demo";
import FilterPanelDemo from "@/components/demos/filter-panel-demo";
import FrameStripDemo from "@/components/demos/frame-strip-demo";
import GenSettingsBarDemo from "@/components/demos/gen-settings-bar-demo";
import GenerationGridDemo from "@/components/demos/generation-grid-demo";
import GenerationPanelDemo from "@/components/demos/generation-panel-demo";
import GenerationQueueDemo from "@/components/demos/generation-queue-demo";
import GenerationShellDemo from "@/components/demos/generation-shell-demo";
import GenerationWizardDemo from "@/components/demos/generation-wizard-demo";
import HeroOmniboxDemo from "@/components/demos/hero-omnibox-demo";
import HomeShellDemo from "@/components/demos/home-shell-demo";
import InlineGeneratePopupDemo from "@/components/demos/inline-generate-popup-demo";
import KbdDemo from "@/components/demos/kbd-demo";
import LibraryShellDemo from "@/components/demos/library-shell-demo";
import MediaPromptBarDemo from "@/components/demos/media-prompt-bar-demo";
import MemberGateRowDemo from "@/components/demos/member-gate-row-demo";
import ModalityRailDemo from "@/components/demos/modality-rail-demo";
import ModeTabsDemo from "@/components/demos/mode-tabs-demo";
import ModelPickerDemo from "@/components/demos/model-picker-demo";
import NotebookShellDemo from "@/components/demos/notebook-shell-demo";
import OnboardingWizardDemo from "@/components/demos/onboarding-wizard-demo";
import ParameterPanelDemo from "@/components/demos/parameter-panel-demo";
import PaywallMessageDemo from "@/components/demos/paywall-message-demo";
import PermissionPromptDemo from "@/components/demos/permission-prompt-demo";
import PresetGridDemo from "@/components/demos/preset-grid-demo";
import PreviewTileDemo from "@/components/demos/preview-tile-demo";
import PricingTableDemo from "@/components/demos/pricing-table-demo";
import PromoCardDemo from "@/components/demos/promo-card-demo";
import PropertyInspectorDemo from "@/components/demos/property-inspector-demo";
import QuotaMeterDemo from "@/components/demos/quota-meter-demo";
import QuoteReplyDemo from "@/components/demos/quote-reply-demo";
import RateLimitBannerDemo from "@/components/demos/rate-limit-banner-demo";
import RecentGridDemo from "@/components/demos/recent-grid-demo";
import RecommendationCardDemo from "@/components/demos/recommendation-card-demo";
import RecordListDemo from "@/components/demos/record-list-demo";
import RecordsShellDemo from "@/components/demos/records-shell-demo";
import ReferenceStripDemo from "@/components/demos/reference-strip-demo";
import RenderQueueDemo from "@/components/demos/render-queue-demo";
import ResetAffordanceDemo from "@/components/demos/reset-affordance-demo";
import ResultCardDemo from "@/components/demos/result-card-demo";
import RunButtonDemo from "@/components/demos/run-button-demo";
import RunInspectorDemo from "@/components/demos/run-inspector-demo";
import SafetyBlockDemo from "@/components/demos/safety-block-demo";
import SectionHeaderDemo from "@/components/demos/section-header-demo";
import SelectionToolbarDemo from "@/components/demos/selection-toolbar-demo";
import SettingsDialogDemo from "@/components/demos/settings-dialog-demo";
import SettingsShellDemo from "@/components/demos/settings-shell-demo";
import ShortcutsSheetDemo from "@/components/demos/shortcuts-sheet-demo";
import SidebarNavDemo from "@/components/demos/sidebar-nav-demo";
import SkillMenuDemo from "@/components/demos/skill-menu-demo";
import SlotSummaryDemo from "@/components/demos/slot-summary-demo";
import SourceCardsDemo from "@/components/demos/source-cards-demo";
import SourcePanelDemo from "@/components/demos/source-panel-demo";
import StatReadoutDemo from "@/components/demos/stat-readout-demo";
import StemMixerDemo from "@/components/demos/stem-mixer-demo";
import StudioShellDemo from "@/components/demos/studio-shell-demo";
import SuggestionChipsDemo from "@/components/demos/suggestion-chips-demo";
import TaskTrayDemo from "@/components/demos/task-tray-demo";
import TemplateDetailDemo from "@/components/demos/template-detail-demo";
import ThreadListDemo from "@/components/demos/thread-list-demo";
import TimeRulerDemo from "@/components/demos/time-ruler-demo";
import TimelineShellDemo from "@/components/demos/timeline-shell-demo";
import ToolPanelDemo from "@/components/demos/tool-panel-demo";
import TraceTimelineDemo from "@/components/demos/trace-timeline-demo";
import TrackLaneDemo from "@/components/demos/track-lane-demo";
import TrackListDemo from "@/components/demos/track-list-demo";
import TranscriptEditorDemo from "@/components/demos/transcript-editor-demo";
import TransportControlsDemo from "@/components/demos/transport-controls-demo";
import TrustDialogDemo from "@/components/demos/trust-dialog-demo";
import TtsComposerDemo from "@/components/demos/tts-composer-demo";
import UsageDashboardDemo from "@/components/demos/usage-dashboard-demo";
import VoiceCloneRecorderDemo from "@/components/demos/voice-clone-recorder-demo";
import WaveformEditorDemo from "@/components/demos/waveform-editor-demo";
import WhatsNewDemo from "@/components/demos/whats-new-demo";
import WorkspaceSwitcherDemo from "@/components/demos/workspace-switcher-demo";

export const demos: Record<string, ComponentType> = {
  "account-menu": AccountMenuDemo,
  "action-stack": ActionStackDemo,
  "ai-doc-block": AiDocBlockDemo,
  "ai-tools-menu": AiToolsMenuDemo,
  "answer-block": AnswerBlockDemo,
  "app-sidebar": AppSidebarDemo,
  "app-topbar": AppTopbarDemo,
  "approval-card": ApprovalCardDemo,
  "artifact-grid": ArtifactGridDemo,
  "artifact-shell": ArtifactShellDemo,
  "asset-detail": AssetDetailDemo,
  "asset-library": AssetLibraryDemo,
  "auth-shell": AuthShellDemo,
  "autonomy-selector": AutonomySelectorDemo,
  "chat-shell": ChatShellDemo,
  "choice-chips": ChoiceChipsDemo,
  "citation-ref": CitationRefDemo,
  "coach-mark": CoachMarkDemo,
  "compare-viewer": CompareViewerDemo,
  "connection-manager": ConnectionManagerDemo,
  "context-chips": ContextChipsDemo,
  "context-toolbar": ContextToolbarDemo,
  "cost-chip": CostChipDemo,
  "credits-indicator": CreditsIndicatorDemo,
  "data-views": DataViewsDemo,
  "date-section": DateSectionDemo,
  "detail-view-shell": DetailViewShellDemo,
  "diff-review": DiffReviewDemo,
  "disclaimer-note": DisclaimerNoteDemo,
  "docs-shell": DocsShellDemo,
  "drawing-tools": DrawingToolsDemo,
  "empty-state": EmptyStateDemo,
  "entity-row": EntityRowDemo,
  "env-status": EnvStatusDemo,
  "escalation-handoff": EscalationHandoffDemo,
  "explore-gallery": ExploreGalleryDemo,
  "explore-shell": ExploreShellDemo,
  "feature-announcement": FeatureAnnouncementDemo,
  "feature-card-row": FeatureCardRowDemo,
  "feedback": FeedbackDemo,
  "field-row": FieldRowDemo,
  "filter-bar": FilterBarDemo,
  "filter-panel": FilterPanelDemo,
  "frame-strip": FrameStripDemo,
  "gen-settings-bar": GenSettingsBarDemo,
  "generation-grid": GenerationGridDemo,
  "generation-panel": GenerationPanelDemo,
  "generation-queue": GenerationQueueDemo,
  "generation-shell": GenerationShellDemo,
  "generation-wizard": GenerationWizardDemo,
  "hero-omnibox": HeroOmniboxDemo,
  "home-shell": HomeShellDemo,
  "inline-generate-popup": InlineGeneratePopupDemo,
  "kbd": KbdDemo,
  "library-shell": LibraryShellDemo,
  "media-prompt-bar": MediaPromptBarDemo,
  "member-gate-row": MemberGateRowDemo,
  "modality-rail": ModalityRailDemo,
  "mode-tabs": ModeTabsDemo,
  "model-picker": ModelPickerDemo,
  "notebook-shell": NotebookShellDemo,
  "onboarding-wizard": OnboardingWizardDemo,
  "parameter-panel": ParameterPanelDemo,
  "paywall-message": PaywallMessageDemo,
  "permission-prompt": PermissionPromptDemo,
  "preset-grid": PresetGridDemo,
  "preview-tile": PreviewTileDemo,
  "pricing-table": PricingTableDemo,
  "promo-card": PromoCardDemo,
  "property-inspector": PropertyInspectorDemo,
  "quota-meter": QuotaMeterDemo,
  "quote-reply": QuoteReplyDemo,
  "rate-limit-banner": RateLimitBannerDemo,
  "recent-grid": RecentGridDemo,
  "recommendation-card": RecommendationCardDemo,
  "record-list": RecordListDemo,
  "records-shell": RecordsShellDemo,
  "reference-strip": ReferenceStripDemo,
  "render-queue": RenderQueueDemo,
  "reset-affordance": ResetAffordanceDemo,
  "result-card": ResultCardDemo,
  "run-button": RunButtonDemo,
  "run-inspector": RunInspectorDemo,
  "safety-block": SafetyBlockDemo,
  "section-header": SectionHeaderDemo,
  "selection-toolbar": SelectionToolbarDemo,
  "settings-dialog": SettingsDialogDemo,
  "settings-shell": SettingsShellDemo,
  "shortcuts-sheet": ShortcutsSheetDemo,
  "sidebar-nav": SidebarNavDemo,
  "skill-menu": SkillMenuDemo,
  "slot-summary": SlotSummaryDemo,
  "source-cards": SourceCardsDemo,
  "source-panel": SourcePanelDemo,
  "stat-readout": StatReadoutDemo,
  "stem-mixer": StemMixerDemo,
  "studio-shell": StudioShellDemo,
  "suggestion-chips": SuggestionChipsDemo,
  "task-tray": TaskTrayDemo,
  "template-detail": TemplateDetailDemo,
  "thread-list": ThreadListDemo,
  "time-ruler": TimeRulerDemo,
  "timeline-shell": TimelineShellDemo,
  "tool-panel": ToolPanelDemo,
  "trace-timeline": TraceTimelineDemo,
  "track-lane": TrackLaneDemo,
  "track-list": TrackListDemo,
  "transcript-editor": TranscriptEditorDemo,
  "transport-controls": TransportControlsDemo,
  "trust-dialog": TrustDialogDemo,
  "tts-composer": TtsComposerDemo,
  "usage-dashboard": UsageDashboardDemo,
  "voice-clone-recorder": VoiceCloneRecorderDemo,
  "waveform-editor": WaveformEditorDemo,
  "whats-new": WhatsNewDemo,
  "workspace-switcher": WorkspaceSwitcherDemo,
};
