// GENERATED by scripts/gen-wiring.mts. Do not edit.
import type { ComponentDocs } from "./component-docs";

import { AccountMenuDocs } from "@/content/components/account-menu.docs";
import { ActionStackDocs } from "@/content/components/action-stack.docs";
import { AiDocBlockDocs } from "@/content/components/ai-doc-block.docs";
import { AiToolsMenuDocs } from "@/content/components/ai-tools-menu.docs";
import { AnswerBlockDocs } from "@/content/components/answer-block.docs";
import { AppSidebarDocs } from "@/content/components/app-sidebar.docs";
import { AppTopbarDocs } from "@/content/components/app-topbar.docs";
import { ApprovalCardDocs } from "@/content/components/approval-card.docs";
import { ArtifactGridDocs } from "@/content/components/artifact-grid.docs";
import { ArtifactShellDocs } from "@/content/components/artifact-shell.docs";
import { AssetDetailDocs } from "@/content/components/asset-detail.docs";
import { AssetLibraryDocs } from "@/content/components/asset-library.docs";
import { AuthShellDocs } from "@/content/components/auth-shell.docs";
import { AutonomySelectorDocs } from "@/content/components/autonomy-selector.docs";
import { ChatShellDocs } from "@/content/components/chat-shell.docs";
import { CitationRefDocs } from "@/content/components/citation-ref.docs";
import { CoachMarkDocs } from "@/content/components/coach-mark.docs";
import { CompareViewerDocs } from "@/content/components/compare-viewer.docs";
import { ConnectionManagerDocs } from "@/content/components/connection-manager.docs";
import { ContextChipsDocs } from "@/content/components/context-chips.docs";
import { ContextToolbarDocs } from "@/content/components/context-toolbar.docs";
import { CreditsIndicatorDocs } from "@/content/components/credits-indicator.docs";
import { DataViewsDocs } from "@/content/components/data-views.docs";
import { DetailViewShellDocs } from "@/content/components/detail-view-shell.docs";
import { DiffReviewDocs } from "@/content/components/diff-review.docs";
import { DisclaimerNoteDocs } from "@/content/components/disclaimer-note.docs";
import { DocsShellDocs } from "@/content/components/docs-shell.docs";
import { DrawingToolsDocs } from "@/content/components/drawing-tools.docs";
import { EmptyStateDocs } from "@/content/components/empty-state.docs";
import { EnvStatusDocs } from "@/content/components/env-status.docs";
import { EscalationHandoffDocs } from "@/content/components/escalation-handoff.docs";
import { ExploreGalleryDocs } from "@/content/components/explore-gallery.docs";
import { ExploreShellDocs } from "@/content/components/explore-shell.docs";
import { FeatureAnnouncementDocs } from "@/content/components/feature-announcement.docs";
import { FeatureCardRowDocs } from "@/content/components/feature-card-row.docs";
import { FeedbackDocs } from "@/content/components/feedback.docs";
import { FilterPanelDocs } from "@/content/components/filter-panel.docs";
import { FrameStripDocs } from "@/content/components/frame-strip.docs";
import { GenerationGridDocs } from "@/content/components/generation-grid.docs";
import { GenerationPanelDocs } from "@/content/components/generation-panel.docs";
import { GenerationQueueDocs } from "@/content/components/generation-queue.docs";
import { GenerationShellDocs } from "@/content/components/generation-shell.docs";
import { GenerationWizardDocs } from "@/content/components/generation-wizard.docs";
import { HeroOmniboxDocs } from "@/content/components/hero-omnibox.docs";
import { HomeShellDocs } from "@/content/components/home-shell.docs";
import { InlineGeneratePopupDocs } from "@/content/components/inline-generate-popup.docs";
import { LibraryShellDocs } from "@/content/components/library-shell.docs";
import { MediaPromptBarDocs } from "@/content/components/media-prompt-bar.docs";
import { MemberGateRowDocs } from "@/content/components/member-gate-row.docs";
import { ModalityRailDocs } from "@/content/components/modality-rail.docs";
import { ModeTabsDocs } from "@/content/components/mode-tabs.docs";
import { ModelPickerDocs } from "@/content/components/model-picker.docs";
import { NotebookShellDocs } from "@/content/components/notebook-shell.docs";
import { OnboardingWizardDocs } from "@/content/components/onboarding-wizard.docs";
import { ParameterPanelDocs } from "@/content/components/parameter-panel.docs";
import { PaywallMessageDocs } from "@/content/components/paywall-message.docs";
import { PermissionPromptDocs } from "@/content/components/permission-prompt.docs";
import { PresetGridDocs } from "@/content/components/preset-grid.docs";
import { PricingTableDocs } from "@/content/components/pricing-table.docs";
import { PromoCardDocs } from "@/content/components/promo-card.docs";
import { PropertyInspectorDocs } from "@/content/components/property-inspector.docs";
import { QuotaMeterDocs } from "@/content/components/quota-meter.docs";
import { QuoteReplyDocs } from "@/content/components/quote-reply.docs";
import { RateLimitBannerDocs } from "@/content/components/rate-limit-banner.docs";
import { RecentGridDocs } from "@/content/components/recent-grid.docs";
import { RecommendationCardDocs } from "@/content/components/recommendation-card.docs";
import { RecordListDocs } from "@/content/components/record-list.docs";
import { RecordsShellDocs } from "@/content/components/records-shell.docs";
import { ReferenceStripDocs } from "@/content/components/reference-strip.docs";
import { RenderQueueDocs } from "@/content/components/render-queue.docs";
import { ResultCardDocs } from "@/content/components/result-card.docs";
import { RunButtonDocs } from "@/content/components/run-button.docs";
import { RunInspectorDocs } from "@/content/components/run-inspector.docs";
import { SafetyBlockDocs } from "@/content/components/safety-block.docs";
import { SelectionToolbarDocs } from "@/content/components/selection-toolbar.docs";
import { SettingsDialogDocs } from "@/content/components/settings-dialog.docs";
import { SettingsShellDocs } from "@/content/components/settings-shell.docs";
import { SidebarNavDocs } from "@/content/components/sidebar-nav.docs";
import { SkillMenuDocs } from "@/content/components/skill-menu.docs";
import { SlotSummaryDocs } from "@/content/components/slot-summary.docs";
import { SourceCardsDocs } from "@/content/components/source-cards.docs";
import { SourcePanelDocs } from "@/content/components/source-panel.docs";
import { StemMixerDocs } from "@/content/components/stem-mixer.docs";
import { StudioShellDocs } from "@/content/components/studio-shell.docs";
import { SuggestionChipsDocs } from "@/content/components/suggestion-chips.docs";
import { TaskTrayDocs } from "@/content/components/task-tray.docs";
import { TemplateDetailDocs } from "@/content/components/template-detail.docs";
import { TimeRulerDocs } from "@/content/components/time-ruler.docs";
import { TimelineShellDocs } from "@/content/components/timeline-shell.docs";
import { ToolPanelDocs } from "@/content/components/tool-panel.docs";
import { TraceTimelineDocs } from "@/content/components/trace-timeline.docs";
import { TrackLaneDocs } from "@/content/components/track-lane.docs";
import { TrackListDocs } from "@/content/components/track-list.docs";
import { TranscriptEditorDocs } from "@/content/components/transcript-editor.docs";
import { TransportControlsDocs } from "@/content/components/transport-controls.docs";
import { TrustDialogDocs } from "@/content/components/trust-dialog.docs";
import { TtsComposerDocs } from "@/content/components/tts-composer.docs";
import { UsageDashboardDocs } from "@/content/components/usage-dashboard.docs";
import { VoiceCloneRecorderDocs } from "@/content/components/voice-clone-recorder.docs";
import { WaveformEditorDocs } from "@/content/components/waveform-editor.docs";
import { WhatsNewDocs } from "@/content/components/whats-new.docs";
import { WorkspaceSwitcherDocs } from "@/content/components/workspace-switcher.docs";

export const componentDocs: Record<string, ComponentDocs> = {
  "account-menu": AccountMenuDocs,
  "action-stack": ActionStackDocs,
  "ai-doc-block": AiDocBlockDocs,
  "ai-tools-menu": AiToolsMenuDocs,
  "answer-block": AnswerBlockDocs,
  "app-sidebar": AppSidebarDocs,
  "app-topbar": AppTopbarDocs,
  "approval-card": ApprovalCardDocs,
  "artifact-grid": ArtifactGridDocs,
  "artifact-shell": ArtifactShellDocs,
  "asset-detail": AssetDetailDocs,
  "asset-library": AssetLibraryDocs,
  "auth-shell": AuthShellDocs,
  "autonomy-selector": AutonomySelectorDocs,
  "chat-shell": ChatShellDocs,
  "citation-ref": CitationRefDocs,
  "coach-mark": CoachMarkDocs,
  "compare-viewer": CompareViewerDocs,
  "connection-manager": ConnectionManagerDocs,
  "context-chips": ContextChipsDocs,
  "context-toolbar": ContextToolbarDocs,
  "credits-indicator": CreditsIndicatorDocs,
  "data-views": DataViewsDocs,
  "detail-view-shell": DetailViewShellDocs,
  "diff-review": DiffReviewDocs,
  "disclaimer-note": DisclaimerNoteDocs,
  "docs-shell": DocsShellDocs,
  "drawing-tools": DrawingToolsDocs,
  "empty-state": EmptyStateDocs,
  "env-status": EnvStatusDocs,
  "escalation-handoff": EscalationHandoffDocs,
  "explore-gallery": ExploreGalleryDocs,
  "explore-shell": ExploreShellDocs,
  "feature-announcement": FeatureAnnouncementDocs,
  "feature-card-row": FeatureCardRowDocs,
  "feedback": FeedbackDocs,
  "filter-panel": FilterPanelDocs,
  "frame-strip": FrameStripDocs,
  "generation-grid": GenerationGridDocs,
  "generation-panel": GenerationPanelDocs,
  "generation-queue": GenerationQueueDocs,
  "generation-shell": GenerationShellDocs,
  "generation-wizard": GenerationWizardDocs,
  "hero-omnibox": HeroOmniboxDocs,
  "home-shell": HomeShellDocs,
  "inline-generate-popup": InlineGeneratePopupDocs,
  "library-shell": LibraryShellDocs,
  "media-prompt-bar": MediaPromptBarDocs,
  "member-gate-row": MemberGateRowDocs,
  "modality-rail": ModalityRailDocs,
  "mode-tabs": ModeTabsDocs,
  "model-picker": ModelPickerDocs,
  "notebook-shell": NotebookShellDocs,
  "onboarding-wizard": OnboardingWizardDocs,
  "parameter-panel": ParameterPanelDocs,
  "paywall-message": PaywallMessageDocs,
  "permission-prompt": PermissionPromptDocs,
  "preset-grid": PresetGridDocs,
  "pricing-table": PricingTableDocs,
  "promo-card": PromoCardDocs,
  "property-inspector": PropertyInspectorDocs,
  "quota-meter": QuotaMeterDocs,
  "quote-reply": QuoteReplyDocs,
  "rate-limit-banner": RateLimitBannerDocs,
  "recent-grid": RecentGridDocs,
  "recommendation-card": RecommendationCardDocs,
  "record-list": RecordListDocs,
  "records-shell": RecordsShellDocs,
  "reference-strip": ReferenceStripDocs,
  "render-queue": RenderQueueDocs,
  "result-card": ResultCardDocs,
  "run-button": RunButtonDocs,
  "run-inspector": RunInspectorDocs,
  "safety-block": SafetyBlockDocs,
  "selection-toolbar": SelectionToolbarDocs,
  "settings-dialog": SettingsDialogDocs,
  "settings-shell": SettingsShellDocs,
  "sidebar-nav": SidebarNavDocs,
  "skill-menu": SkillMenuDocs,
  "slot-summary": SlotSummaryDocs,
  "source-cards": SourceCardsDocs,
  "source-panel": SourcePanelDocs,
  "stem-mixer": StemMixerDocs,
  "studio-shell": StudioShellDocs,
  "suggestion-chips": SuggestionChipsDocs,
  "task-tray": TaskTrayDocs,
  "template-detail": TemplateDetailDocs,
  "time-ruler": TimeRulerDocs,
  "timeline-shell": TimelineShellDocs,
  "tool-panel": ToolPanelDocs,
  "trace-timeline": TraceTimelineDocs,
  "track-lane": TrackLaneDocs,
  "track-list": TrackListDocs,
  "transcript-editor": TranscriptEditorDocs,
  "transport-controls": TransportControlsDocs,
  "trust-dialog": TrustDialogDocs,
  "tts-composer": TtsComposerDocs,
  "usage-dashboard": UsageDashboardDocs,
  "voice-clone-recorder": VoiceCloneRecorderDocs,
  "waveform-editor": WaveformEditorDocs,
  "whats-new": WhatsNewDocs,
  "workspace-switcher": WorkspaceSwitcherDocs,
};
