// GENERATED by scripts/gen-wiring.mts. Do not edit.
import type { ComponentType } from "react";
import type { PatternDocs } from "./pattern-docs";

export const patternModules: Record<string, PatternDocs> = {};
export const patternDemos: Record<string, ComponentType> = {};
