import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { parseCatalogTables } from "./lib/parse-catalog";
import type { FamilyId, ManifestItem, ManifestStatus } from "../lib/manifest-types";

const here = dirname(fileURLToPath(import.meta.url));
const CATALOG_MD = join(here, "../../../docs/design-system/catalog.md");
const OUT = join(here, "../lib/catalog.manifest.ts");

/**
 * Cut records that are not a whole family. O5 `flow-shell` was cut by D9 and is
 * struck through in catalog.md (`~~`flow-shell`~~`); the parser reads the name
 * out of the backticks and cannot see the strikethrough, so it is named here.
 */
const CUT_IDS = new Set(["O5"]);

/** Wave assignment per decisions.md §5. G is cut, so it has no wave. */
const WAVE_BY_FAMILY: Record<FamilyId, number> = {
  A: 1, B: 2, C: 2, D: 3, E: 4, F: 4, G: 0, H: 6, I: 6, J: 7, K: 8, L: 9, M: 10, N: 11, O: 2,
};

/** The 14 items already in the registry, and the deps their code actually imports. */
const SHIPPED: Record<string, { shadcn?: string[]; consumes?: string[]; npm?: string[] }> = {
  kbd: {},
  "cost-chip": { npm: ["lucide-react"] },
  "date-section": {},
  "choice-chips": {},
  "filter-bar": { npm: ["lucide-react"] },
  "field-row": { consumes: ["reset-affordance"] },
  "gen-settings-bar": {},
  "preview-tile": {},
  "entity-row": {},
  "section-header": {},
  "reset-affordance": {},
  "stat-readout": {},
  "shortcuts-sheet": { shadcn: ["dialog"], consumes: ["kbd"] },
  "thread-list": {
    shadcn: ["button", "input", "dropdown-menu", "alert-dialog"],
    consumes: ["date-section"],
    npm: ["lucide-react"],
  },
};

const titleCase = (name: string) =>
  name
    .split("-")
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(" ");

const isFamilyId = (family: string): family is FamilyId =>
  /^[A-O]$/.test(family);

const rows = parseCatalogTables(readFileSync(CATALOG_MD, "utf8"));

const items: ManifestItem[] = rows.map((row) => {
  if (!isFamilyId(row.family)) {
    throw new Error(`gen:manifest — unrecognized family "${row.family}" on row ${row.id}`);
  }
  const family = row.family;

  const shipped = SHIPPED[row.name];
  const layer: ManifestItem["layer"] =
    family === "A" ? "primitive" : family === "O" ? "block" : "component";
  const status: ManifestStatus =
    family === "G" || CUT_IDS.has(row.id) ? "cut" : shipped ? "shipped" : "planned";

  return {
    id: row.id,
    name: row.name,
    title: titleCase(row.name),
    description: row.description,
    family,
    layer,
    status,
    wave: WAVE_BY_FAMILY[family] ?? 0,
    base: row.base,
    shadcn: shipped?.shadcn ?? [],
    consumes: shipped?.consumes ?? [],
    npm: shipped?.npm ?? [],
    states: row.states,
    specAnchor: `component-specs.md#${row.id.toLowerCase()}-${row.name.toLowerCase()}`,
    ...(shipped ? { contractExempt: true as const } : {}),
  };
});

const body = `// GENERATED by scripts/gen-manifest.mts from docs/design-system/catalog.md.
// Bootstrap only — regenerating overwrites hand edits. After the first run this
// file is edited by hand and by scripts/new-component.mts.
import type { ManifestItem } from "./manifest-types";

export const MANIFEST: ManifestItem[] = ${JSON.stringify(items, null, 2)};
`;

writeFileSync(OUT, body);
console.log(`gen:manifest — wrote ${items.length} items to lib/catalog.manifest.ts`);
