import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { MANIFEST } from "../lib/catalog.manifest";

const here = dirname(fileURLToPath(import.meta.url));
const check = process.argv.includes("--check");

const pascal = (name: string) =>
  name
    .split("-")
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");

const shipped = MANIFEST.filter((i) => i.status === "shipped")
  .map((i) => i.name)
  .sort();

const demosSource = `// GENERATED by scripts/gen-wiring.mts. Do not edit.
import type { ComponentType } from "react";

${shipped.map((n) => `import ${pascal(n)}Demo from "@/components/demos/${n}-demo";`).join("\n")}

export const demos: Record<string, ComponentType> = {
${shipped.map((n) => `  "${n}": ${pascal(n)}Demo,`).join("\n")}
};
`;

const withDocs = shipped.filter((n) => existsSync(join(here, `../content/components/${n}.docs.tsx`)));

// When no docs modules exist yet, importing `ComponentDocs` for an empty map
// would be an unused import (eslint's @typescript-eslint/no-unused-vars flags
// it). Only import the type — and the per-component doc modules — when there
// is at least one entry; otherwise type the empty map with `never` so it
// still accurately says "no docs exist yet" without an unused import.
const docsSource =
  withDocs.length === 0
    ? `// GENERATED by scripts/gen-wiring.mts. Do not edit.
export const componentDocs: Record<string, never> = {};
`
    : `// GENERATED by scripts/gen-wiring.mts. Do not edit.
import type { ComponentDocs } from "./component-docs";

${withDocs.map((n) => `import { ${pascal(n)}Docs } from "@/content/components/${n}.docs";`).join("\n")}

export const componentDocs: Record<string, ComponentDocs> = {
${withDocs.map((n) => `  "${n}": ${pascal(n)}Docs,`).join("\n")}
};
`;

const patternsDir = join(here, "../content/patterns");
const patternSlugs = existsSync(patternsDir)
  ? readdirSync(patternsDir)
      .filter((f) => f.endsWith(".pattern.tsx"))
      .map((f) => f.replace(/\.pattern\.tsx$/, ""))
      .sort()
  : [];
const withComposition = patternSlugs.filter((s) =>
  existsSync(join(here, `../components/demos/patterns/${s}-demo.tsx`)),
);

// Both types are used by the annotations, so the empty case keeps them: the
// pages typecheck against these maps before any module exists.
const patternsSource =
  patternSlugs.length === 0
    ? `// GENERATED by scripts/gen-wiring.mts. Do not edit.
import type { ComponentType } from "react";
import type { PatternDocs } from "./pattern-docs";

export const patternModules: Record<string, PatternDocs> = {};
export const patternDemos: Record<string, ComponentType> = {};
`
    : `// GENERATED by scripts/gen-wiring.mts. Do not edit.
import type { ComponentType } from "react";
import type { PatternDocs } from "./pattern-docs";

${patternSlugs.map((s) => `import { ${pascal(s)}Pattern } from "@/content/patterns/${s}.pattern";`).join("\n")}
${withComposition.map((s) => `import ${pascal(s)}PatternDemo from "@/components/demos/patterns/${s}-demo";`).join("\n")}

export const patternModules: Record<string, PatternDocs> = {
${patternSlugs.map((s) => `  "${s}": ${pascal(s)}Pattern,`).join("\n")}
};

export const patternDemos: Record<string, ComponentType> = {
${withComposition.map((s) => `  "${s}": ${pascal(s)}PatternDemo,`).join("\n")}
};
`;

const targets = [
  { path: join(here, "../lib/demos.generated.ts"), source: demosSource },
  { path: join(here, "../lib/docs.generated.ts"), source: docsSource },
  { path: join(here, "../lib/patterns.generated.ts"), source: patternsSource },
];

let stale = 0;
for (const { path, source } of targets) {
  if (check) {
    const current = existsSync(path) ? readFileSync(path, "utf8") : "";
    if (current !== source) {
      stale++;
      console.error(`gen:wiring --check — ${path} is stale. Run pnpm gen:wiring.`);
    }
  } else {
    writeFileSync(path, source);
  }
}

if (check && stale) process.exit(1);
console.log(check ? "gen:wiring — wiring is current." : `gen:wiring — wrote ${targets.length} files.`);
