import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { MANIFEST } from "../lib/catalog.manifest";

const root = join(__dirname, "..");
const barrel = join(root, "lib/docs.ru.generated.ts");
const overlayDir = join(root, "content/ru/components");
const shipped = MANIFEST.filter((i) => i.status === "shipped").map((i) => i.name);

describe("gen-wiring output", () => {
  it("emits a Russian docs barrel", () => {
    expect(existsSync(barrel)).toBe(true);
  });

  it("marks the Russian barrel generated", () => {
    const src = readFileSync(barrel, "utf8");
    expect(src.startsWith("// GENERATED by scripts/gen-wiring.mts. Do not edit.")).toBe(true);
  });

  it("exports componentDocsRu", () => {
    expect(readFileSync(barrel, "utf8")).toContain("export const componentDocsRu");
  });

  it("has an entry for every Russian overlay file on disk", () => {
    // Before Task 8 this directory does not exist and the generator takes its
    // empty-map branch, so there is nothing to assert. After Task 8 it pins the
    // barrel to the filesystem.
    if (!existsSync(overlayDir)) return;
    const src = readFileSync(barrel, "utf8");
    // The generator deliberately filters overlay files against the shipped manifest,
    // so the test must filter the same way or it fails while asserting correct code.
    // A stray overlay file (for a non-shipped component) should not enter the barrel.
    for (const file of readdirSync(overlayDir)) {
      if (!file.endsWith(".ts")) continue;
      const name = file.replace(/\.ts$/, "");
      if (!shipped.includes(name)) continue;
      expect(src).toContain(`"${name}"`);
    }
  });
});
