// Mounts the docs demos inside a scaffolded consumer so the harness can render
// every item against the installed copies, not the docs sources.
//
// Three moves:
//  1. Copy components/demos/<name>-demo.tsx into <consumer>/harness/demos/.
//  2. Map every registry source path to its installed target in the consumer's
//     tsconfig `paths`, so a demo's `@/registry/super-ai/x` import resolves to
//     `components/super-ai/x` (or `lib/x` for lib items) — exact keys, listed
//     before `@/*`, one per registry file, read from registry.json.
//  3. Write app/harness/[name]/page.tsx (one static route per demo, wrapped in
//     <main data-harness-item>) and app/harness/page.tsx (an index).
// It also prints the `@/components/ui/*` names the demos import, one per line
// between UI_IMPORTS_BEGIN and UI_IMPORTS_END, so the shell can `shadcn add`
// the ones no item pulled in.
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { HARNESS_ITEMS } from "./items";

const consumer = process.argv[2];
if (!consumer) {
  console.error("usage: tsx harness/scaffold-consumer.mts <consumerDir>");
  process.exit(2);
}
const docs = fileURLToPath(new URL("../", import.meta.url));
const registry = JSON.parse(readFileSync(join(docs, "registry.json"), "utf8")) as {
  items: { files?: { path: string; target?: string }[] }[];
};

// 1. demos
const demosDir = join(consumer, "harness", "demos");
mkdirSync(demosDir, { recursive: true });
const uiImports = new Set<string>();
for (const item of HARNESS_ITEMS) {
  const src = join(docs, "components", "demos", `${item.name}-demo.tsx`);
  copyFileSync(src, join(demosDir, `${item.name}-demo.tsx`));
  for (const m of readFileSync(src, "utf8").matchAll(/from "@\/components\/ui\/([a-z0-9-]+)"/g))
    uiImports.add(m[1]);
}
const pascal = (s: string) => s.replace(/(^|-)([a-z0-9])/g, (_, __, c: string) => c.toUpperCase());
writeFileSync(
  join(consumer, "harness", "demos.generated.ts"),
  [
    "// GENERATED by scaffold-consumer.mts. Do not edit.",
    'import type { ComponentType } from "react";',
    ...HARNESS_ITEMS.map((i) => `import ${pascal(i.name)}Demo from "./demos/${i.name}-demo";`),
    "",
    "export const demos: Record<string, ComponentType> = {",
    ...HARNESS_ITEMS.map((i) => `  "${i.name}": ${pascal(i.name)}Demo,`),
    "};",
    "export const names = Object.keys(demos);",
    "",
  ].join("\n"),
);

// 2. tsconfig paths
const tsconfigPath = join(consumer, "tsconfig.json");
const tsconfig = JSON.parse(readFileSync(tsconfigPath, "utf8"));
const strip = (p: string) => p.replace(/\.(tsx|ts)$/, "");
const itemPaths: Record<string, string[]> = {};
for (const item of registry.items) {
  for (const f of item.files ?? []) {
    if (!f.target) continue;
    itemPaths[`@/${strip(f.path)}`] = [`./${strip(f.target)}`];
  }
}
tsconfig.compilerOptions.paths = { ...itemPaths, ...(tsconfig.compilerOptions.paths ?? {}) };
writeFileSync(tsconfigPath, `${JSON.stringify(tsconfig, null, 2)}\n`);

// 3. routes
mkdirSync(join(consumer, "app", "harness", "[name]"), { recursive: true });
writeFileSync(
  join(consumer, "app", "harness", "[name]", "page.tsx"),
  `import { notFound } from "next/navigation";

import { demos, names } from "@/harness/demos.generated";

export const dynamicParams = false;

export function generateStaticParams() {
  return names.map((name) => ({ name }));
}

export default async function HarnessPage({ params }: { params: Promise<{ name: string }> }) {
  const { name } = await params;
  const Demo = demos[name];
  if (!Demo) notFound();
  return (
    <main data-harness-item={name} className="min-h-svh p-8">
      <Demo />
    </main>
  );
}
`,
);
writeFileSync(
  join(consumer, "app", "harness", "page.tsx"),
  `import Link from "next/link";

import { names } from "@/harness/demos.generated";

export default function HarnessIndex() {
  return (
    <main className="p-8">
      <h1 className="mb-4 text-lg font-medium">Preset harness</h1>
      <ul className="columns-3 text-sm">
        {names.map((name) => (
          <li key={name}>
            <Link className="underline" href={\`/harness/\${name}\`}>
              {name}
            </Link>
          </li>
        ))}
      </ul>
    </main>
  );
}
`,
);

console.log(
  `scaffold-consumer: ${HARNESS_ITEMS.length} demos, ${Object.keys(itemPaths).length} path aliases`,
);
console.log("UI_IMPORTS_BEGIN");
for (const name of [...uiImports].sort()) console.log(name);
console.log("UI_IMPORTS_END");
